db.define_table('empresa',
		                 Field('proprietario','reference auth_user', label='Proprietario', writable=False, readable=False, notnull=True, default=1),
		                 Field('razaosocial', 'string', label='Razão Social',requires = IS_UPPER()),
		                 Field('nomefantasia', 'string', label='Nome Fantasia',requires = IS_UPPER()),
		                 Field('cnpj', 'string', label='CNPJ',requires = IS_UPPER()),
		                 Field('inscricaoestarual', 'string', label='Insc. Est',requires = IS_UPPER()),
		                 Field('inscricaomunicipal', 'string', label='Insc. Mun',requires = IS_UPPER()),
		                 Field('crt', 'string', label='CRT',requires = IS_UPPER()),
		                 Field('cep', 'string', label='CEP',requires = IS_UPPER()),
		                 Field('lougradouro', 'string', label='Lougradouro',requires = IS_UPPER()),
		                 Field('numero', 'string', label='Numero',requires = IS_UPPER()),
		                 Field('bairro', 'string', label='Bairro',requires = IS_UPPER()),
		                 Field('uf', 'string', label='UF',requires = IS_UPPER()),
		                 Field('cidade', 'string', label='Cidade',requires = IS_UPPER()),
		                 Field('complemento', 'string', label='Complemento',requires = IS_UPPER()),
		                 Field('email', 'string', label='Email',requires = IS_UPPER()),
		                 Field('telefone', 'string', label='Telefone',requires = IS_UPPER()),
		                 Field('celular', 'string', label='Celular',requires = IS_UPPER()),
		                 Field('ativo', 'boolean', writable=False, readable=False, default=True),
		                 auth.signature,
		                 format='%(nomefantasia)s')
		
db.define_table('pessoa',
		                 Field('empresa','reference empresa', label='empresa'),
		                 Field('tipo', 'string', label='Tipo',requires = IS_UPPER()),
		                 Field('razaosocial_nome', 'string', label='RS/NC',requires = IS_UPPER()),
		                 Field('sexo', 'string', label='Sexo',requires = IS_UPPER()),
		                 Field('estado_civil', 'string', label='Est. Civil',requires = IS_UPPER()),
		                 Field('apelido_nome_fantasia', 'string', label='AP/NF',requires = IS_UPPER()),
		                 Field('cpf', 'string', label='CPF',requires = IS_UPPER()),
		                 Field('org_espedidor_cpf', 'string', label='org esp.',requires = IS_UPPER()),
		                 Field('rg', 'string', label='RG',requires = IS_UPPER()),
		                 Field('org_espedidor_rg', 'string', label='org esp.',requires = IS_UPPER()),
		                 Field('cep', 'string', label='CEP',requires = IS_UPPER()),
		                 Field('lougradouro', 'string', label='Lougradouro',requires = IS_UPPER()),
		                 Field('numero', 'string', label='Numero',requires = IS_UPPER()),
		                 Field('bairro', 'string', label='Bairro',requires = IS_UPPER()),
		                 Field('uf', 'string', label='UF',requires = IS_UPPER()),
		                 Field('cidade', 'string', label='Cidade',requires = IS_UPPER()),
		                 Field('complemento', 'string', label='Complemento',requires = IS_UPPER()),
		                 Field('email', 'string', label='Email',requires = IS_UPPER()),
		                 Field('telefone', 'string', label='Telefone',requires = IS_UPPER()),
		                 Field('celular', 'string', label='Celular',requires = IS_UPPER()),
		                 Field('qcontratos', 'integer', label='Qcontratos', writable=False, readable=False, notnull=True, default=0),
		                 Field('ativo', 'boolean', writable=False, readable=False, default=True),
		                 auth.signature,
		                 format='%(apelido_nome_fantasia)s')
		
db.define_table('pessoa_fisica',
		                 Field('pessoa','reference pessoa', label='Pessoa'),
		                 Field('nome', 'string', label='Nome',requires = IS_UPPER()),
		                 Field('conjuge','reference pessoa', label='Cônjuge'),
		                 Field('nomepai','reference pessoa', label='Nome Pai'),
		                 Field('nomemae','reference pessoa', label='Nome Mãe'),
		                 Field('data_nascimento', 'date', label="Data Nasc", default=request.now, requires = IS_DATE(format=('%d-%m-%Y')), notnull=True),
		                 Field('estado_civil', 'string', label='Est. Civil',requires = IS_UPPER()),
		                 Field('profissao', 'string', label='Profissão',requires = IS_UPPER()),
		                 Field('localtrabalho', 'string', label='Local Trabalho',requires = IS_UPPER()),
		                 Field('telefoneempresa', 'string', label='Telefone Empresa',requires = IS_UPPER()),
		                 Field('ativo', 'boolean', writable=False, readable=False, default=True),
		                 auth.signature,
		                 format='%(nome)s')
		
db.define_table('loteamento',
		                 Field('empresa','reference empresa', label='empresa'),
		                 Field('descricao', 'string', label='Descricao',requires = IS_UPPER()),
		                 Field('razaosocial', 'string', label='Razão Social',requires = IS_UPPER()),
		                 Field('nomefantasia', 'string', label='Nome Fantasia',requires = IS_UPPER()),
		                 Field('cnpj', 'string', label='CNPJ',requires = IS_UPPER()),
		                 Field('inscricaoestarual', 'string', label='Insc. Est',requires = IS_UPPER()),
		                 Field('inscricaomunicipal', 'string', label='Insc. Mun',requires = IS_UPPER()),
		                 Field('crt', 'string', label='CRT',requires = IS_UPPER()),
		                 Field('cep', 'string', label='CEP',requires = IS_UPPER()),
		                 Field('bairro', 'string', label='Bairro',requires = IS_UPPER()),
		                 Field('uf', 'string', label='UF',requires = IS_UPPER()),
		                 Field('cidade', 'string', label='Cidade',requires = IS_UPPER()),
		                 Field('complemento', 'string', label='Complemento',requires = IS_UPPER()),
		                 Field('email', 'string', label='Email',requires = IS_UPPER()),
		                 Field('telefone', 'string', label='Telefone',requires = IS_UPPER()),
		                 Field('celular', 'string', label='Celular',requires = IS_UPPER()),
		                 Field('quant_imoveis', 'integer', label='Quant Imoveis', writable=False, readable=False, notnull=True, default=0),
		                 Field('quant_contratos', 'integer', label='Quant Contratos', writable=False, readable=False, notnull=True, default=0),
		                 Field('valor_recebido', 'double', label='Valor Recebido', writable=False, readable=False, notnull=True, default=0),
		                 Field('valor_receber', 'double', label='Valor à Receber', writable=False, readable=False, notnull=True, default=0),
		                 Field('ativo', 'boolean', writable=False, readable=False, default=True),
		                 auth.signature,
		                 format='%(descricao)s')
		
db.define_table('lote',
		                 Field('empresa','reference empresa', label='empresa'),
		                 Field('loteamento','reference loteamento', label='loteamento'),
		                 Field('tipo', 'string', label='Tipo',requires = IS_UPPER()),
		                 Field('descricao', 'string', label='Descricao',requires = IS_UPPER()),
		                 Field('cod_referencia', 'string', label='Descricao',requires = IS_UPPER()),
		                 Field('valor_venda', 'double', label='Valor Venda', writable=False, readable=False, notnull=True, default=0),
		                 Field('status', 'string', label='Status',requires = IS_UPPER()),
		                 Field('observacao', 'string', label='Observação',requires = IS_UPPER()),
		                 Field('memorial_descritivo', 'string', label='Mem. Descritivo',requires = IS_UPPER()),
		                 Field('nome', 'string', label='Lote',requires = IS_UPPER()),
		                 Field('extremos_leste', 'string', label='Extremo Leste',requires = IS_UPPER()),
		                 Field('metragem_leste', 'double', label='Metrs. Leste', notnull=True, default=0),
		                 Field('extremos_oeste', 'string', label='Extremo Oeste',requires = IS_UPPER()),
		                 Field('metragem_oeste', 'double', label='Metrs. Oeste', notnull=True, default=0),
		                 Field('extremos_norte', 'string', label='Extremo Norte',requires = IS_UPPER()),
		                 Field('metragem_norte', 'double', label='Metrs. Norte', notnull=True, default=0),
		                 Field('extremos_sul', 'string', label='Extremo Sul',requires = IS_UPPER()),
		                 Field('metragem_sul', 'double', label='Metrs. Sul', notnull=True, default=0),
		                 Field('area_frente', 'double', label='Area de Frente', notnull=True, default=0),
		                 Field('area_fundo', 'double', label='Area de Fundo', notnull=True, default=0),
		                 Field('cep', 'string', label='CEP',requires = IS_UPPER()),
		                 Field('lougradouro', 'string', label='Lougradouro',requires = IS_UPPER()),
		                 Field('numero', 'string', label='Numero',requires = IS_UPPER()),
		                 Field('complemento', 'string', label='Complemento',requires = IS_UPPER()),
		                 Field('bairro', 'string', label='Bairro',requires = IS_UPPER()),
		                 Field('uf', 'string', label='UF',requires = IS_UPPER()),
		                 Field('cidade', 'string', label='Cidade',requires = IS_UPPER()),
		                 Field('ponto_referencia', 'string', label='Ponto de Referência',requires = IS_UPPER()),
		                 Field('quant_parcelas_total', 'integer', label='Parcelas Total', writable=False, readable=False, notnull=True, default=0),
		                 Field('quant_parcelas_pagas', 'integer', label='Parcelas Pagas', writable=False, readable=False, notnull=True, default=0),
		                 Field('valor_recebido', 'double', label='Valor Recebido', writable=False, readable=False, notnull=True, default=0),
		                 Field('valor_receber', 'double', label='Valor à Receber', writable=False, readable=False, notnull=True, default=0),
		                 Field('ativo', 'boolean', writable=False, readable=False, default=True),
		                 auth.signature,
		                 format='%(nome)s')
